version: '3.7'

networks:
  dockerapi-dev:
    driver: bridge

services:
  dockerapi:
    image: dockerimage_api:latest
    depends_on:
      - postgresvolume
    build:
      context: ./
      dockerfile: ./DockerAPI/Dockerfile
    ports:
      - "8000:80"
    networks:
      - dockerapi-dev

  postgresvolume:
    image: postgres:latest
    ports:
      - "9876:5432"
    restart: always
    volumes:
      - ./DockerPostgresDB/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=teste
      - POSTGRES_USER=rei
    networks:
      - dockerapi-dev

  dockerblazor:
    image: docker_blazor:latest
    depends_on:
      - dockerapi
    build:
      context: ./DockerBlazor
    ports:
      - "8080:80"
    networks:
      - dockerapi-dev

volumes:
  db_volume:
